# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

download_data <- function(url) {
    .Call('_rnaseq_download_data', PACKAGE = 'rnaseq', url)
}

parallel_vector_addition <- function(a, b) {
    .Call('_rnaseq_parallel_vector_addition', PACKAGE = 'rnaseq', a, b)
}

