# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fancy Print Messages
#' @description
#' Prints messages with fancy decorations.
#'
#' @param messages A character vector of messages to print.
#' @return None. Messages are printed to the console.
#' @examples
#' fancy_print(c("Hello", "World"))
#' @useDynLib rnaseq, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
fancy_print <- function(messages) {
    invisible(.Call('_rnaseq_fancy_print', PACKAGE = 'rnaseq', messages))
}

